apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-service-gateway
  labels:
    app: k8s-service-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-service-gateway
  template:
    metadata:
      labels:
        app: k8s-service-gateway
    spec:
      containers:
        - name: containerized-gateway
          image: tanerdiler/service-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8762