apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-service-orders
  labels:
    app: k8s-service-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-service-orders
  template:
    metadata:
      labels:
        app: k8s-service-orders
    spec:
      containers:
        - name: containerized-orders
          image: tanerdiler/service-orders-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 2222